/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AAndLogicalPart extends PLogicalPart
{
    private PLogicalValue _logicalValue_;
    private TAnd _and_;

    public AAndLogicalPart()
    {
        // Constructor
    }

    public AAndLogicalPart(
        @SuppressWarnings("hiding") PLogicalValue _logicalValue_,
        @SuppressWarnings("hiding") TAnd _and_)
    {
        // Constructor
        setLogicalValue(_logicalValue_);

        setAnd(_and_);

    }

    @Override
    public Object clone()
    {
        return new AAndLogicalPart(
            cloneNode(this._logicalValue_),
            cloneNode(this._and_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAndLogicalPart(this);
    }

    public PLogicalValue getLogicalValue()
    {
        return this._logicalValue_;
    }

    public void setLogicalValue(PLogicalValue node)
    {
        if(this._logicalValue_ != null)
        {
            this._logicalValue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._logicalValue_ = node;
    }

    public TAnd getAnd()
    {
        return this._and_;
    }

    public void setAnd(TAnd node)
    {
        if(this._and_ != null)
        {
            this._and_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._and_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._logicalValue_)
            + toString(this._and_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._logicalValue_ == child)
        {
            this._logicalValue_ = null;
            return;
        }

        if(this._and_ == child)
        {
            this._and_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._logicalValue_ == oldChild)
        {
            setLogicalValue((PLogicalValue) newChild);
            return;
        }

        if(this._and_ == oldChild)
        {
            setAnd((TAnd) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
