/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import java.util.*;
import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AAPrintFunction extends PPrintFunction
{
    private TPrint _print_;
    private PId _fileNumber_;
    private TComma _comma_;
    private final LinkedList<PPrintFunctionPart> _printFunctionPart_ = new LinkedList<PPrintFunctionPart>();
    private PValue _value_;

    public AAPrintFunction()
    {
        // Constructor
    }

    public AAPrintFunction(
        @SuppressWarnings("hiding") TPrint _print_,
        @SuppressWarnings("hiding") PId _fileNumber_,
        @SuppressWarnings("hiding") TComma _comma_,
        @SuppressWarnings("hiding") List<PPrintFunctionPart> _printFunctionPart_,
        @SuppressWarnings("hiding") PValue _value_)
    {
        // Constructor
        setPrint(_print_);

        setFileNumber(_fileNumber_);

        setComma(_comma_);

        setPrintFunctionPart(_printFunctionPart_);

        setValue(_value_);

    }

    @Override
    public Object clone()
    {
        return new AAPrintFunction(
            cloneNode(this._print_),
            cloneNode(this._fileNumber_),
            cloneNode(this._comma_),
            cloneList(this._printFunctionPart_),
            cloneNode(this._value_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAPrintFunction(this);
    }

    public TPrint getPrint()
    {
        return this._print_;
    }

    public void setPrint(TPrint node)
    {
        if(this._print_ != null)
        {
            this._print_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._print_ = node;
    }

    public PId getFileNumber()
    {
        return this._fileNumber_;
    }

    public void setFileNumber(PId node)
    {
        if(this._fileNumber_ != null)
        {
            this._fileNumber_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fileNumber_ = node;
    }

    public TComma getComma()
    {
        return this._comma_;
    }

    public void setComma(TComma node)
    {
        if(this._comma_ != null)
        {
            this._comma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comma_ = node;
    }

    public LinkedList<PPrintFunctionPart> getPrintFunctionPart()
    {
        return this._printFunctionPart_;
    }

    public void setPrintFunctionPart(List<PPrintFunctionPart> list)
    {
        this._printFunctionPart_.clear();
        this._printFunctionPart_.addAll(list);
        for(PPrintFunctionPart e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    public PValue getValue()
    {
        return this._value_;
    }

    public void setValue(PValue node)
    {
        if(this._value_ != null)
        {
            this._value_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._value_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._print_)
            + toString(this._fileNumber_)
            + toString(this._comma_)
            + toString(this._printFunctionPart_)
            + toString(this._value_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._print_ == child)
        {
            this._print_ = null;
            return;
        }

        if(this._fileNumber_ == child)
        {
            this._fileNumber_ = null;
            return;
        }

        if(this._comma_ == child)
        {
            this._comma_ = null;
            return;
        }

        if(this._printFunctionPart_.remove(child))
        {
            return;
        }

        if(this._value_ == child)
        {
            this._value_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._print_ == oldChild)
        {
            setPrint((TPrint) newChild);
            return;
        }

        if(this._fileNumber_ == oldChild)
        {
            setFileNumber((PId) newChild);
            return;
        }

        if(this._comma_ == oldChild)
        {
            setComma((TComma) newChild);
            return;
        }

        for(ListIterator<PPrintFunctionPart> i = this._printFunctionPart_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PPrintFunctionPart) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._value_ == oldChild)
        {
            setValue((PValue) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
