/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AAttributeDecInFileStmt extends PFileStmt
{
    private PAttributeDecIn _attributeDecIn_;
    private PGeneralStmt _generalStmt_;

    public AAttributeDecInFileStmt()
    {
        // Constructor
    }

    public AAttributeDecInFileStmt(
        @SuppressWarnings("hiding") PAttributeDecIn _attributeDecIn_,
        @SuppressWarnings("hiding") PGeneralStmt _generalStmt_)
    {
        // Constructor
        setAttributeDecIn(_attributeDecIn_);

        setGeneralStmt(_generalStmt_);

    }

    @Override
    public Object clone()
    {
        return new AAttributeDecInFileStmt(
            cloneNode(this._attributeDecIn_),
            cloneNode(this._generalStmt_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAttributeDecInFileStmt(this);
    }

    public PAttributeDecIn getAttributeDecIn()
    {
        return this._attributeDecIn_;
    }

    public void setAttributeDecIn(PAttributeDecIn node)
    {
        if(this._attributeDecIn_ != null)
        {
            this._attributeDecIn_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._attributeDecIn_ = node;
    }

    public PGeneralStmt getGeneralStmt()
    {
        return this._generalStmt_;
    }

    public void setGeneralStmt(PGeneralStmt node)
    {
        if(this._generalStmt_ != null)
        {
            this._generalStmt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._generalStmt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._attributeDecIn_)
            + toString(this._generalStmt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._attributeDecIn_ == child)
        {
            this._attributeDecIn_ = null;
            return;
        }

        if(this._generalStmt_ == child)
        {
            this._generalStmt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._attributeDecIn_ == oldChild)
        {
            setAttributeDecIn((PAttributeDecIn) newChild);
            return;
        }

        if(this._generalStmt_ == oldChild)
        {
            setGeneralStmt((PGeneralStmt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
