/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AAutoFitFunctionFunctionStmt extends PFunctionStmt
{
    private PAutoFitFunction _autoFitFunction_;
    private PGeneralStmt _generalStmt_;

    public AAutoFitFunctionFunctionStmt()
    {
        // Constructor
    }

    public AAutoFitFunctionFunctionStmt(
        @SuppressWarnings("hiding") PAutoFitFunction _autoFitFunction_,
        @SuppressWarnings("hiding") PGeneralStmt _generalStmt_)
    {
        // Constructor
        setAutoFitFunction(_autoFitFunction_);

        setGeneralStmt(_generalStmt_);

    }

    @Override
    public Object clone()
    {
        return new AAutoFitFunctionFunctionStmt(
            cloneNode(this._autoFitFunction_),
            cloneNode(this._generalStmt_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAutoFitFunctionFunctionStmt(this);
    }

    public PAutoFitFunction getAutoFitFunction()
    {
        return this._autoFitFunction_;
    }

    public void setAutoFitFunction(PAutoFitFunction node)
    {
        if(this._autoFitFunction_ != null)
        {
            this._autoFitFunction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._autoFitFunction_ = node;
    }

    public PGeneralStmt getGeneralStmt()
    {
        return this._generalStmt_;
    }

    public void setGeneralStmt(PGeneralStmt node)
    {
        if(this._generalStmt_ != null)
        {
            this._generalStmt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._generalStmt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._autoFitFunction_)
            + toString(this._generalStmt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._autoFitFunction_ == child)
        {
            this._autoFitFunction_ = null;
            return;
        }

        if(this._generalStmt_ == child)
        {
            this._generalStmt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._autoFitFunction_ == oldChild)
        {
            setAutoFitFunction((PAutoFitFunction) newChild);
            return;
        }

        if(this._generalStmt_ == oldChild)
        {
            setGeneralStmt((PGeneralStmt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
