/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ACellExcelColumn extends PExcelColumn
{
    private PExcelCell _excelCell_;
    private TMethodChainingOperator _methodChainingOperator_;
    private PExcelColumneValue _excelColumneValue_;

    public ACellExcelColumn()
    {
        // Constructor
    }

    public ACellExcelColumn(
        @SuppressWarnings("hiding") PExcelCell _excelCell_,
        @SuppressWarnings("hiding") TMethodChainingOperator _methodChainingOperator_,
        @SuppressWarnings("hiding") PExcelColumneValue _excelColumneValue_)
    {
        // Constructor
        setExcelCell(_excelCell_);

        setMethodChainingOperator(_methodChainingOperator_);

        setExcelColumneValue(_excelColumneValue_);

    }

    @Override
    public Object clone()
    {
        return new ACellExcelColumn(
            cloneNode(this._excelCell_),
            cloneNode(this._methodChainingOperator_),
            cloneNode(this._excelColumneValue_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACellExcelColumn(this);
    }

    public PExcelCell getExcelCell()
    {
        return this._excelCell_;
    }

    public void setExcelCell(PExcelCell node)
    {
        if(this._excelCell_ != null)
        {
            this._excelCell_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._excelCell_ = node;
    }

    public TMethodChainingOperator getMethodChainingOperator()
    {
        return this._methodChainingOperator_;
    }

    public void setMethodChainingOperator(TMethodChainingOperator node)
    {
        if(this._methodChainingOperator_ != null)
        {
            this._methodChainingOperator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._methodChainingOperator_ = node;
    }

    public PExcelColumneValue getExcelColumneValue()
    {
        return this._excelColumneValue_;
    }

    public void setExcelColumneValue(PExcelColumneValue node)
    {
        if(this._excelColumneValue_ != null)
        {
            this._excelColumneValue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._excelColumneValue_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._excelCell_)
            + toString(this._methodChainingOperator_)
            + toString(this._excelColumneValue_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._excelCell_ == child)
        {
            this._excelCell_ = null;
            return;
        }

        if(this._methodChainingOperator_ == child)
        {
            this._methodChainingOperator_ = null;
            return;
        }

        if(this._excelColumneValue_ == child)
        {
            this._excelColumneValue_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._excelCell_ == oldChild)
        {
            setExcelCell((PExcelCell) newChild);
            return;
        }

        if(this._methodChainingOperator_ == oldChild)
        {
            setMethodChainingOperator((TMethodChainingOperator) newChild);
            return;
        }

        if(this._excelColumneValue_ == oldChild)
        {
            setExcelColumneValue((PExcelColumneValue) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
