/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AChrFunctionValue extends PValue
{
    private PChrFunction _chrFunction_;

    public AChrFunctionValue()
    {
        // Constructor
    }

    public AChrFunctionValue(
        @SuppressWarnings("hiding") PChrFunction _chrFunction_)
    {
        // Constructor
        setChrFunction(_chrFunction_);

    }

    @Override
    public Object clone()
    {
        return new AChrFunctionValue(
            cloneNode(this._chrFunction_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAChrFunctionValue(this);
    }

    public PChrFunction getChrFunction()
    {
        return this._chrFunction_;
    }

    public void setChrFunction(PChrFunction node)
    {
        if(this._chrFunction_ != null)
        {
            this._chrFunction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._chrFunction_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._chrFunction_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._chrFunction_ == child)
        {
            this._chrFunction_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._chrFunction_ == oldChild)
        {
            setChrFunction((PChrFunction) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
