/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ACloseFileFunctionFunctionStmt extends PFunctionStmt
{
    private PCloseFileFunction _closeFileFunction_;
    private PGeneralStmt _generalStmt_;

    public ACloseFileFunctionFunctionStmt()
    {
        // Constructor
    }

    public ACloseFileFunctionFunctionStmt(
        @SuppressWarnings("hiding") PCloseFileFunction _closeFileFunction_,
        @SuppressWarnings("hiding") PGeneralStmt _generalStmt_)
    {
        // Constructor
        setCloseFileFunction(_closeFileFunction_);

        setGeneralStmt(_generalStmt_);

    }

    @Override
    public Object clone()
    {
        return new ACloseFileFunctionFunctionStmt(
            cloneNode(this._closeFileFunction_),
            cloneNode(this._generalStmt_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACloseFileFunctionFunctionStmt(this);
    }

    public PCloseFileFunction getCloseFileFunction()
    {
        return this._closeFileFunction_;
    }

    public void setCloseFileFunction(PCloseFileFunction node)
    {
        if(this._closeFileFunction_ != null)
        {
            this._closeFileFunction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._closeFileFunction_ = node;
    }

    public PGeneralStmt getGeneralStmt()
    {
        return this._generalStmt_;
    }

    public void setGeneralStmt(PGeneralStmt node)
    {
        if(this._generalStmt_ != null)
        {
            this._generalStmt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._generalStmt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._closeFileFunction_)
            + toString(this._generalStmt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._closeFileFunction_ == child)
        {
            this._closeFileFunction_ = null;
            return;
        }

        if(this._generalStmt_ == child)
        {
            this._generalStmt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._closeFileFunction_ == oldChild)
        {
            setCloseFileFunction((PCloseFileFunction) newChild);
            return;
        }

        if(this._generalStmt_ == oldChild)
        {
            setGeneralStmt((PGeneralStmt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
