/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AColumnSetHiddenFunction extends PSetHiddenFunction
{
    private PExcelColumn _excelColumn_;
    private TMethodChainingOperator _methodChainingOperator_;
    private THidden _hidden_;
    private TAllocation _allocation_;
    private PBooleanValue _booleanValue_;

    public AColumnSetHiddenFunction()
    {
        // Constructor
    }

    public AColumnSetHiddenFunction(
        @SuppressWarnings("hiding") PExcelColumn _excelColumn_,
        @SuppressWarnings("hiding") TMethodChainingOperator _methodChainingOperator_,
        @SuppressWarnings("hiding") THidden _hidden_,
        @SuppressWarnings("hiding") TAllocation _allocation_,
        @SuppressWarnings("hiding") PBooleanValue _booleanValue_)
    {
        // Constructor
        setExcelColumn(_excelColumn_);

        setMethodChainingOperator(_methodChainingOperator_);

        setHidden(_hidden_);

        setAllocation(_allocation_);

        setBooleanValue(_booleanValue_);

    }

    @Override
    public Object clone()
    {
        return new AColumnSetHiddenFunction(
            cloneNode(this._excelColumn_),
            cloneNode(this._methodChainingOperator_),
            cloneNode(this._hidden_),
            cloneNode(this._allocation_),
            cloneNode(this._booleanValue_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAColumnSetHiddenFunction(this);
    }

    public PExcelColumn getExcelColumn()
    {
        return this._excelColumn_;
    }

    public void setExcelColumn(PExcelColumn node)
    {
        if(this._excelColumn_ != null)
        {
            this._excelColumn_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._excelColumn_ = node;
    }

    public TMethodChainingOperator getMethodChainingOperator()
    {
        return this._methodChainingOperator_;
    }

    public void setMethodChainingOperator(TMethodChainingOperator node)
    {
        if(this._methodChainingOperator_ != null)
        {
            this._methodChainingOperator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._methodChainingOperator_ = node;
    }

    public THidden getHidden()
    {
        return this._hidden_;
    }

    public void setHidden(THidden node)
    {
        if(this._hidden_ != null)
        {
            this._hidden_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._hidden_ = node;
    }

    public TAllocation getAllocation()
    {
        return this._allocation_;
    }

    public void setAllocation(TAllocation node)
    {
        if(this._allocation_ != null)
        {
            this._allocation_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._allocation_ = node;
    }

    public PBooleanValue getBooleanValue()
    {
        return this._booleanValue_;
    }

    public void setBooleanValue(PBooleanValue node)
    {
        if(this._booleanValue_ != null)
        {
            this._booleanValue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._booleanValue_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._excelColumn_)
            + toString(this._methodChainingOperator_)
            + toString(this._hidden_)
            + toString(this._allocation_)
            + toString(this._booleanValue_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._excelColumn_ == child)
        {
            this._excelColumn_ = null;
            return;
        }

        if(this._methodChainingOperator_ == child)
        {
            this._methodChainingOperator_ = null;
            return;
        }

        if(this._hidden_ == child)
        {
            this._hidden_ = null;
            return;
        }

        if(this._allocation_ == child)
        {
            this._allocation_ = null;
            return;
        }

        if(this._booleanValue_ == child)
        {
            this._booleanValue_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._excelColumn_ == oldChild)
        {
            setExcelColumn((PExcelColumn) newChild);
            return;
        }

        if(this._methodChainingOperator_ == oldChild)
        {
            setMethodChainingOperator((TMethodChainingOperator) newChild);
            return;
        }

        if(this._hidden_ == oldChild)
        {
            setHidden((THidden) newChild);
            return;
        }

        if(this._allocation_ == oldChild)
        {
            setAllocation((TAllocation) newChild);
            return;
        }

        if(this._booleanValue_ == oldChild)
        {
            setBooleanValue((PBooleanValue) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
