/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ACSngFunctionValue extends PValue
{
    private PCSngFunction _cSngFunction_;

    public ACSngFunctionValue()
    {
        // Constructor
    }

    public ACSngFunctionValue(
        @SuppressWarnings("hiding") PCSngFunction _cSngFunction_)
    {
        // Constructor
        setCSngFunction(_cSngFunction_);

    }

    @Override
    public Object clone()
    {
        return new ACSngFunctionValue(
            cloneNode(this._cSngFunction_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACSngFunctionValue(this);
    }

    public PCSngFunction getCSngFunction()
    {
        return this._cSngFunction_;
    }

    public void setCSngFunction(PCSngFunction node)
    {
        if(this._cSngFunction_ != null)
        {
            this._cSngFunction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._cSngFunction_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._cSngFunction_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._cSngFunction_ == child)
        {
            this._cSngFunction_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._cSngFunction_ == oldChild)
        {
            setCSngFunction((PCSngFunction) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
