/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ADebugPrintFunctionFunctionStmt extends PFunctionStmt
{
    private PDebugPrintFunction _debugPrintFunction_;
    private PGeneralStmt _generalStmt_;

    public ADebugPrintFunctionFunctionStmt()
    {
        // Constructor
    }

    public ADebugPrintFunctionFunctionStmt(
        @SuppressWarnings("hiding") PDebugPrintFunction _debugPrintFunction_,
        @SuppressWarnings("hiding") PGeneralStmt _generalStmt_)
    {
        // Constructor
        setDebugPrintFunction(_debugPrintFunction_);

        setGeneralStmt(_generalStmt_);

    }

    @Override
    public Object clone()
    {
        return new ADebugPrintFunctionFunctionStmt(
            cloneNode(this._debugPrintFunction_),
            cloneNode(this._generalStmt_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADebugPrintFunctionFunctionStmt(this);
    }

    public PDebugPrintFunction getDebugPrintFunction()
    {
        return this._debugPrintFunction_;
    }

    public void setDebugPrintFunction(PDebugPrintFunction node)
    {
        if(this._debugPrintFunction_ != null)
        {
            this._debugPrintFunction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._debugPrintFunction_ = node;
    }

    public PGeneralStmt getGeneralStmt()
    {
        return this._generalStmt_;
    }

    public void setGeneralStmt(PGeneralStmt node)
    {
        if(this._generalStmt_ != null)
        {
            this._generalStmt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._generalStmt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._debugPrintFunction_)
            + toString(this._generalStmt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._debugPrintFunction_ == child)
        {
            this._debugPrintFunction_ = null;
            return;
        }

        if(this._generalStmt_ == child)
        {
            this._generalStmt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._debugPrintFunction_ == oldChild)
        {
            setDebugPrintFunction((PDebugPrintFunction) newChild);
            return;
        }

        if(this._generalStmt_ == oldChild)
        {
            setGeneralStmt((PGeneralStmt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
