/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AEqualLogicalOperator extends PLogicalOperator
{
    private TAllocation _allocation_;

    public AEqualLogicalOperator()
    {
        // Constructor
    }

    public AEqualLogicalOperator(
        @SuppressWarnings("hiding") TAllocation _allocation_)
    {
        // Constructor
        setAllocation(_allocation_);

    }

    @Override
    public Object clone()
    {
        return new AEqualLogicalOperator(
            cloneNode(this._allocation_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEqualLogicalOperator(this);
    }

    public TAllocation getAllocation()
    {
        return this._allocation_;
    }

    public void setAllocation(TAllocation node)
    {
        if(this._allocation_ != null)
        {
            this._allocation_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._allocation_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._allocation_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._allocation_ == child)
        {
            this._allocation_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._allocation_ == oldChild)
        {
            setAllocation((TAllocation) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
