/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AExitForIfStmtOneLineValue extends PIfStmtOneLineValue
{
    private TExitFor _exitFor_;

    public AExitForIfStmtOneLineValue()
    {
        // Constructor
    }

    public AExitForIfStmtOneLineValue(
        @SuppressWarnings("hiding") TExitFor _exitFor_)
    {
        // Constructor
        setExitFor(_exitFor_);

    }

    @Override
    public Object clone()
    {
        return new AExitForIfStmtOneLineValue(
            cloneNode(this._exitFor_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExitForIfStmtOneLineValue(this);
    }

    public TExitFor getExitFor()
    {
        return this._exitFor_;
    }

    public void setExitFor(TExitFor node)
    {
        if(this._exitFor_ != null)
        {
            this._exitFor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exitFor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exitFor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exitFor_ == child)
        {
            this._exitFor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exitFor_ == oldChild)
        {
            setExitFor((TExitFor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
