/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AFunctionWithoutReturnTypeFileStmt extends PFileStmt
{
    private PFunctionWithoutReturnType _functionWithoutReturnType_;
    private PGeneralStmt _generalStmt_;

    public AFunctionWithoutReturnTypeFileStmt()
    {
        // Constructor
    }

    public AFunctionWithoutReturnTypeFileStmt(
        @SuppressWarnings("hiding") PFunctionWithoutReturnType _functionWithoutReturnType_,
        @SuppressWarnings("hiding") PGeneralStmt _generalStmt_)
    {
        // Constructor
        setFunctionWithoutReturnType(_functionWithoutReturnType_);

        setGeneralStmt(_generalStmt_);

    }

    @Override
    public Object clone()
    {
        return new AFunctionWithoutReturnTypeFileStmt(
            cloneNode(this._functionWithoutReturnType_),
            cloneNode(this._generalStmt_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFunctionWithoutReturnTypeFileStmt(this);
    }

    public PFunctionWithoutReturnType getFunctionWithoutReturnType()
    {
        return this._functionWithoutReturnType_;
    }

    public void setFunctionWithoutReturnType(PFunctionWithoutReturnType node)
    {
        if(this._functionWithoutReturnType_ != null)
        {
            this._functionWithoutReturnType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._functionWithoutReturnType_ = node;
    }

    public PGeneralStmt getGeneralStmt()
    {
        return this._generalStmt_;
    }

    public void setGeneralStmt(PGeneralStmt node)
    {
        if(this._generalStmt_ != null)
        {
            this._generalStmt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._generalStmt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._functionWithoutReturnType_)
            + toString(this._generalStmt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._functionWithoutReturnType_ == child)
        {
            this._functionWithoutReturnType_ = null;
            return;
        }

        if(this._generalStmt_ == child)
        {
            this._generalStmt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._functionWithoutReturnType_ == oldChild)
        {
            setFunctionWithoutReturnType((PFunctionWithoutReturnType) newChild);
            return;
        }

        if(this._generalStmt_ == oldChild)
        {
            setGeneralStmt((PGeneralStmt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
