/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AGotoCall extends PGotoCall
{
    private TGoto _goto_;
    private TIdToken _idToken_;

    public AGotoCall()
    {
        // Constructor
    }

    public AGotoCall(
        @SuppressWarnings("hiding") TGoto _goto_,
        @SuppressWarnings("hiding") TIdToken _idToken_)
    {
        // Constructor
        setGoto(_goto_);

        setIdToken(_idToken_);

    }

    @Override
    public Object clone()
    {
        return new AGotoCall(
            cloneNode(this._goto_),
            cloneNode(this._idToken_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGotoCall(this);
    }

    public TGoto getGoto()
    {
        return this._goto_;
    }

    public void setGoto(TGoto node)
    {
        if(this._goto_ != null)
        {
            this._goto_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._goto_ = node;
    }

    public TIdToken getIdToken()
    {
        return this._idToken_;
    }

    public void setIdToken(TIdToken node)
    {
        if(this._idToken_ != null)
        {
            this._idToken_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._idToken_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._goto_)
            + toString(this._idToken_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._goto_ == child)
        {
            this._goto_ = null;
            return;
        }

        if(this._idToken_ == child)
        {
            this._idToken_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._goto_ == oldChild)
        {
            setGoto((TGoto) newChild);
            return;
        }

        if(this._idToken_ == oldChild)
        {
            setIdToken((TIdToken) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
