/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import java.util.*;
import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AIfStmtOneLine extends PIfStmtOneLine
{
    private TIf _if_;
    private PValue _value_;
    private TThen _then_;
    private PIfStmtOneLineValue _first_;
    private final LinkedList<PIfStmtOneLineValue> _ifStmtOneLineValue_ = new LinkedList<PIfStmtOneLineValue>();

    public AIfStmtOneLine()
    {
        // Constructor
    }

    public AIfStmtOneLine(
        @SuppressWarnings("hiding") TIf _if_,
        @SuppressWarnings("hiding") PValue _value_,
        @SuppressWarnings("hiding") TThen _then_,
        @SuppressWarnings("hiding") PIfStmtOneLineValue _first_,
        @SuppressWarnings("hiding") List<PIfStmtOneLineValue> _ifStmtOneLineValue_)
    {
        // Constructor
        setIf(_if_);

        setValue(_value_);

        setThen(_then_);

        setFirst(_first_);

        setIfStmtOneLineValue(_ifStmtOneLineValue_);

    }

    @Override
    public Object clone()
    {
        return new AIfStmtOneLine(
            cloneNode(this._if_),
            cloneNode(this._value_),
            cloneNode(this._then_),
            cloneNode(this._first_),
            cloneList(this._ifStmtOneLineValue_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIfStmtOneLine(this);
    }

    public TIf getIf()
    {
        return this._if_;
    }

    public void setIf(TIf node)
    {
        if(this._if_ != null)
        {
            this._if_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._if_ = node;
    }

    public PValue getValue()
    {
        return this._value_;
    }

    public void setValue(PValue node)
    {
        if(this._value_ != null)
        {
            this._value_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._value_ = node;
    }

    public TThen getThen()
    {
        return this._then_;
    }

    public void setThen(TThen node)
    {
        if(this._then_ != null)
        {
            this._then_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._then_ = node;
    }

    public PIfStmtOneLineValue getFirst()
    {
        return this._first_;
    }

    public void setFirst(PIfStmtOneLineValue node)
    {
        if(this._first_ != null)
        {
            this._first_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._first_ = node;
    }

    public LinkedList<PIfStmtOneLineValue> getIfStmtOneLineValue()
    {
        return this._ifStmtOneLineValue_;
    }

    public void setIfStmtOneLineValue(List<PIfStmtOneLineValue> list)
    {
        this._ifStmtOneLineValue_.clear();
        this._ifStmtOneLineValue_.addAll(list);
        for(PIfStmtOneLineValue e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._if_)
            + toString(this._value_)
            + toString(this._then_)
            + toString(this._first_)
            + toString(this._ifStmtOneLineValue_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._if_ == child)
        {
            this._if_ = null;
            return;
        }

        if(this._value_ == child)
        {
            this._value_ = null;
            return;
        }

        if(this._then_ == child)
        {
            this._then_ = null;
            return;
        }

        if(this._first_ == child)
        {
            this._first_ = null;
            return;
        }

        if(this._ifStmtOneLineValue_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._if_ == oldChild)
        {
            setIf((TIf) newChild);
            return;
        }

        if(this._value_ == oldChild)
        {
            setValue((PValue) newChild);
            return;
        }

        if(this._then_ == oldChild)
        {
            setThen((TThen) newChild);
            return;
        }

        if(this._first_ == oldChild)
        {
            setFirst((PIfStmtOneLineValue) newChild);
            return;
        }

        for(ListIterator<PIfStmtOneLineValue> i = this._ifStmtOneLineValue_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PIfStmtOneLineValue) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
