/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ALCaseFunctionMoreParamCallValues extends PMoreParamCallValues
{
    private PLCaseFunction _lCaseFunction_;

    public ALCaseFunctionMoreParamCallValues()
    {
        // Constructor
    }

    public ALCaseFunctionMoreParamCallValues(
        @SuppressWarnings("hiding") PLCaseFunction _lCaseFunction_)
    {
        // Constructor
        setLCaseFunction(_lCaseFunction_);

    }

    @Override
    public Object clone()
    {
        return new ALCaseFunctionMoreParamCallValues(
            cloneNode(this._lCaseFunction_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALCaseFunctionMoreParamCallValues(this);
    }

    public PLCaseFunction getLCaseFunction()
    {
        return this._lCaseFunction_;
    }

    public void setLCaseFunction(PLCaseFunction node)
    {
        if(this._lCaseFunction_ != null)
        {
            this._lCaseFunction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lCaseFunction_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lCaseFunction_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lCaseFunction_ == child)
        {
            this._lCaseFunction_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lCaseFunction_ == oldChild)
        {
            setLCaseFunction((PLCaseFunction) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
