/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AMultiplicationArithmeticOperator extends PArithmeticOperator
{
    private TMultiplication _multiplication_;

    public AMultiplicationArithmeticOperator()
    {
        // Constructor
    }

    public AMultiplicationArithmeticOperator(
        @SuppressWarnings("hiding") TMultiplication _multiplication_)
    {
        // Constructor
        setMultiplication(_multiplication_);

    }

    @Override
    public Object clone()
    {
        return new AMultiplicationArithmeticOperator(
            cloneNode(this._multiplication_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultiplicationArithmeticOperator(this);
    }

    public TMultiplication getMultiplication()
    {
        return this._multiplication_;
    }

    public void setMultiplication(TMultiplication node)
    {
        if(this._multiplication_ != null)
        {
            this._multiplication_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._multiplication_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._multiplication_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._multiplication_ == child)
        {
            this._multiplication_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._multiplication_ == oldChild)
        {
            setMultiplication((TMultiplication) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
