/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ANegatedArithmeticExpressionInParensArithmeticExpression extends PArithmeticExpression
{
    private TSubtraction _subtraction_;
    private TOpenParen _openParen_;
    private PArithmeticExpression _arithmeticExpression_;
    private TCloseParen _closeParen_;

    public ANegatedArithmeticExpressionInParensArithmeticExpression()
    {
        // Constructor
    }

    public ANegatedArithmeticExpressionInParensArithmeticExpression(
        @SuppressWarnings("hiding") TSubtraction _subtraction_,
        @SuppressWarnings("hiding") TOpenParen _openParen_,
        @SuppressWarnings("hiding") PArithmeticExpression _arithmeticExpression_,
        @SuppressWarnings("hiding") TCloseParen _closeParen_)
    {
        // Constructor
        setSubtraction(_subtraction_);

        setOpenParen(_openParen_);

        setArithmeticExpression(_arithmeticExpression_);

        setCloseParen(_closeParen_);

    }

    @Override
    public Object clone()
    {
        return new ANegatedArithmeticExpressionInParensArithmeticExpression(
            cloneNode(this._subtraction_),
            cloneNode(this._openParen_),
            cloneNode(this._arithmeticExpression_),
            cloneNode(this._closeParen_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANegatedArithmeticExpressionInParensArithmeticExpression(this);
    }

    public TSubtraction getSubtraction()
    {
        return this._subtraction_;
    }

    public void setSubtraction(TSubtraction node)
    {
        if(this._subtraction_ != null)
        {
            this._subtraction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._subtraction_ = node;
    }

    public TOpenParen getOpenParen()
    {
        return this._openParen_;
    }

    public void setOpenParen(TOpenParen node)
    {
        if(this._openParen_ != null)
        {
            this._openParen_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._openParen_ = node;
    }

    public PArithmeticExpression getArithmeticExpression()
    {
        return this._arithmeticExpression_;
    }

    public void setArithmeticExpression(PArithmeticExpression node)
    {
        if(this._arithmeticExpression_ != null)
        {
            this._arithmeticExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._arithmeticExpression_ = node;
    }

    public TCloseParen getCloseParen()
    {
        return this._closeParen_;
    }

    public void setCloseParen(TCloseParen node)
    {
        if(this._closeParen_ != null)
        {
            this._closeParen_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._closeParen_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._subtraction_)
            + toString(this._openParen_)
            + toString(this._arithmeticExpression_)
            + toString(this._closeParen_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._subtraction_ == child)
        {
            this._subtraction_ = null;
            return;
        }

        if(this._openParen_ == child)
        {
            this._openParen_ = null;
            return;
        }

        if(this._arithmeticExpression_ == child)
        {
            this._arithmeticExpression_ = null;
            return;
        }

        if(this._closeParen_ == child)
        {
            this._closeParen_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._subtraction_ == oldChild)
        {
            setSubtraction((TSubtraction) newChild);
            return;
        }

        if(this._openParen_ == oldChild)
        {
            setOpenParen((TOpenParen) newChild);
            return;
        }

        if(this._arithmeticExpression_ == oldChild)
        {
            setArithmeticExpression((PArithmeticExpression) newChild);
            return;
        }

        if(this._closeParen_ == oldChild)
        {
            setCloseParen((TCloseParen) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
