/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AOpenFileOutputModeOpenFileMode extends POpenFileMode
{
    private TOpenFileOutputMode _openFileOutputMode_;

    public AOpenFileOutputModeOpenFileMode()
    {
        // Constructor
    }

    public AOpenFileOutputModeOpenFileMode(
        @SuppressWarnings("hiding") TOpenFileOutputMode _openFileOutputMode_)
    {
        // Constructor
        setOpenFileOutputMode(_openFileOutputMode_);

    }

    @Override
    public Object clone()
    {
        return new AOpenFileOutputModeOpenFileMode(
            cloneNode(this._openFileOutputMode_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOpenFileOutputModeOpenFileMode(this);
    }

    public TOpenFileOutputMode getOpenFileOutputMode()
    {
        return this._openFileOutputMode_;
    }

    public void setOpenFileOutputMode(TOpenFileOutputMode node)
    {
        if(this._openFileOutputMode_ != null)
        {
            this._openFileOutputMode_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._openFileOutputMode_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._openFileOutputMode_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._openFileOutputMode_ == child)
        {
            this._openFileOutputMode_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._openFileOutputMode_ == oldChild)
        {
            setOpenFileOutputMode((TOpenFileOutputMode) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
