/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AOrLogicalPart extends PLogicalPart
{
    private PLogicalValue _logicalValue_;
    private TOr _or_;

    public AOrLogicalPart()
    {
        // Constructor
    }

    public AOrLogicalPart(
        @SuppressWarnings("hiding") PLogicalValue _logicalValue_,
        @SuppressWarnings("hiding") TOr _or_)
    {
        // Constructor
        setLogicalValue(_logicalValue_);

        setOr(_or_);

    }

    @Override
    public Object clone()
    {
        return new AOrLogicalPart(
            cloneNode(this._logicalValue_),
            cloneNode(this._or_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOrLogicalPart(this);
    }

    public PLogicalValue getLogicalValue()
    {
        return this._logicalValue_;
    }

    public void setLogicalValue(PLogicalValue node)
    {
        if(this._logicalValue_ != null)
        {
            this._logicalValue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._logicalValue_ = node;
    }

    public TOr getOr()
    {
        return this._or_;
    }

    public void setOr(TOr node)
    {
        if(this._or_ != null)
        {
            this._or_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._or_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._logicalValue_)
            + toString(this._or_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._logicalValue_ == child)
        {
            this._logicalValue_ = null;
            return;
        }

        if(this._or_ == child)
        {
            this._or_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._logicalValue_ == oldChild)
        {
            setLogicalValue((PLogicalValue) newChild);
            return;
        }

        if(this._or_ == oldChild)
        {
            setOr((TOr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
