/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AOrSimpelConditionPart extends PSimpelConditionPart
{
    private PSimpelConditionValue _simpelConditionValue_;
    private TOr _or_;

    public AOrSimpelConditionPart()
    {
        // Constructor
    }

    public AOrSimpelConditionPart(
        @SuppressWarnings("hiding") PSimpelConditionValue _simpelConditionValue_,
        @SuppressWarnings("hiding") TOr _or_)
    {
        // Constructor
        setSimpelConditionValue(_simpelConditionValue_);

        setOr(_or_);

    }

    @Override
    public Object clone()
    {
        return new AOrSimpelConditionPart(
            cloneNode(this._simpelConditionValue_),
            cloneNode(this._or_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOrSimpelConditionPart(this);
    }

    public PSimpelConditionValue getSimpelConditionValue()
    {
        return this._simpelConditionValue_;
    }

    public void setSimpelConditionValue(PSimpelConditionValue node)
    {
        if(this._simpelConditionValue_ != null)
        {
            this._simpelConditionValue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._simpelConditionValue_ = node;
    }

    public TOr getOr()
    {
        return this._or_;
    }

    public void setOr(TOr node)
    {
        if(this._or_ != null)
        {
            this._or_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._or_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._simpelConditionValue_)
            + toString(this._or_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._simpelConditionValue_ == child)
        {
            this._simpelConditionValue_ = null;
            return;
        }

        if(this._or_ == child)
        {
            this._or_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._simpelConditionValue_ == oldChild)
        {
            setSimpelConditionValue((PSimpelConditionValue) newChild);
            return;
        }

        if(this._or_ == oldChild)
        {
            setOr((TOr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
