/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ARenameFileFunction extends PRenameFileFunction
{
    private TName _name_;
    private PStringValue _oldName_;
    private TAs _as_;
    private PStringValue _newName_;

    public ARenameFileFunction()
    {
        // Constructor
    }

    public ARenameFileFunction(
        @SuppressWarnings("hiding") TName _name_,
        @SuppressWarnings("hiding") PStringValue _oldName_,
        @SuppressWarnings("hiding") TAs _as_,
        @SuppressWarnings("hiding") PStringValue _newName_)
    {
        // Constructor
        setName(_name_);

        setOldName(_oldName_);

        setAs(_as_);

        setNewName(_newName_);

    }

    @Override
    public Object clone()
    {
        return new ARenameFileFunction(
            cloneNode(this._name_),
            cloneNode(this._oldName_),
            cloneNode(this._as_),
            cloneNode(this._newName_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARenameFileFunction(this);
    }

    public TName getName()
    {
        return this._name_;
    }

    public void setName(TName node)
    {
        if(this._name_ != null)
        {
            this._name_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._name_ = node;
    }

    public PStringValue getOldName()
    {
        return this._oldName_;
    }

    public void setOldName(PStringValue node)
    {
        if(this._oldName_ != null)
        {
            this._oldName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._oldName_ = node;
    }

    public TAs getAs()
    {
        return this._as_;
    }

    public void setAs(TAs node)
    {
        if(this._as_ != null)
        {
            this._as_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._as_ = node;
    }

    public PStringValue getNewName()
    {
        return this._newName_;
    }

    public void setNewName(PStringValue node)
    {
        if(this._newName_ != null)
        {
            this._newName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._newName_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._name_)
            + toString(this._oldName_)
            + toString(this._as_)
            + toString(this._newName_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._name_ == child)
        {
            this._name_ = null;
            return;
        }

        if(this._oldName_ == child)
        {
            this._oldName_ = null;
            return;
        }

        if(this._as_ == child)
        {
            this._as_ = null;
            return;
        }

        if(this._newName_ == child)
        {
            this._newName_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._name_ == oldChild)
        {
            setName((TName) newChild);
            return;
        }

        if(this._oldName_ == oldChild)
        {
            setOldName((PStringValue) newChild);
            return;
        }

        if(this._as_ == oldChild)
        {
            setAs((TAs) newChild);
            return;
        }

        if(this._newName_ == oldChild)
        {
            setNewName((PStringValue) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
