/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AReplaceMethodCall extends PMethodCall
{
    private TReplace _replace_;
    private PParamCallList _paramCallList_;

    public AReplaceMethodCall()
    {
        // Constructor
    }

    public AReplaceMethodCall(
        @SuppressWarnings("hiding") TReplace _replace_,
        @SuppressWarnings("hiding") PParamCallList _paramCallList_)
    {
        // Constructor
        setReplace(_replace_);

        setParamCallList(_paramCallList_);

    }

    @Override
    public Object clone()
    {
        return new AReplaceMethodCall(
            cloneNode(this._replace_),
            cloneNode(this._paramCallList_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAReplaceMethodCall(this);
    }

    public TReplace getReplace()
    {
        return this._replace_;
    }

    public void setReplace(TReplace node)
    {
        if(this._replace_ != null)
        {
            this._replace_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._replace_ = node;
    }

    public PParamCallList getParamCallList()
    {
        return this._paramCallList_;
    }

    public void setParamCallList(PParamCallList node)
    {
        if(this._paramCallList_ != null)
        {
            this._paramCallList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._paramCallList_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._replace_)
            + toString(this._paramCallList_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._replace_ == child)
        {
            this._replace_ = null;
            return;
        }

        if(this._paramCallList_ == child)
        {
            this._paramCallList_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._replace_ == oldChild)
        {
            setReplace((TReplace) newChild);
            return;
        }

        if(this._paramCallList_ == oldChild)
        {
            setParamCallList((PParamCallList) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
