/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ARightFunctionParamCallListWithoutParensValue extends PParamCallListWithoutParensValue
{
    private PRightFunction _rightFunction_;

    public ARightFunctionParamCallListWithoutParensValue()
    {
        // Constructor
    }

    public ARightFunctionParamCallListWithoutParensValue(
        @SuppressWarnings("hiding") PRightFunction _rightFunction_)
    {
        // Constructor
        setRightFunction(_rightFunction_);

    }

    @Override
    public Object clone()
    {
        return new ARightFunctionParamCallListWithoutParensValue(
            cloneNode(this._rightFunction_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARightFunctionParamCallListWithoutParensValue(this);
    }

    public PRightFunction getRightFunction()
    {
        return this._rightFunction_;
    }

    public void setRightFunction(PRightFunction node)
    {
        if(this._rightFunction_ != null)
        {
            this._rightFunction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rightFunction_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._rightFunction_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._rightFunction_ == child)
        {
            this._rightFunction_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._rightFunction_ == oldChild)
        {
            setRightFunction((PRightFunction) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
