/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ASetNameExcelFunctionFunctionStmt extends PFunctionStmt
{
    private PSetNameExcelFunction _setNameExcelFunction_;
    private PGeneralStmt _generalStmt_;

    public ASetNameExcelFunctionFunctionStmt()
    {
        // Constructor
    }

    public ASetNameExcelFunctionFunctionStmt(
        @SuppressWarnings("hiding") PSetNameExcelFunction _setNameExcelFunction_,
        @SuppressWarnings("hiding") PGeneralStmt _generalStmt_)
    {
        // Constructor
        setSetNameExcelFunction(_setNameExcelFunction_);

        setGeneralStmt(_generalStmt_);

    }

    @Override
    public Object clone()
    {
        return new ASetNameExcelFunctionFunctionStmt(
            cloneNode(this._setNameExcelFunction_),
            cloneNode(this._generalStmt_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASetNameExcelFunctionFunctionStmt(this);
    }

    public PSetNameExcelFunction getSetNameExcelFunction()
    {
        return this._setNameExcelFunction_;
    }

    public void setSetNameExcelFunction(PSetNameExcelFunction node)
    {
        if(this._setNameExcelFunction_ != null)
        {
            this._setNameExcelFunction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._setNameExcelFunction_ = node;
    }

    public PGeneralStmt getGeneralStmt()
    {
        return this._generalStmt_;
    }

    public void setGeneralStmt(PGeneralStmt node)
    {
        if(this._generalStmt_ != null)
        {
            this._generalStmt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._generalStmt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._setNameExcelFunction_)
            + toString(this._generalStmt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._setNameExcelFunction_ == child)
        {
            this._setNameExcelFunction_ = null;
            return;
        }

        if(this._generalStmt_ == child)
        {
            this._generalStmt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._setNameExcelFunction_ == oldChild)
        {
            setSetNameExcelFunction((PSetNameExcelFunction) newChild);
            return;
        }

        if(this._generalStmt_ == oldChild)
        {
            setGeneralStmt((PGeneralStmt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
