/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ASheetValue extends PValue
{
    private PExcelSheet _excelSheet_;

    public ASheetValue()
    {
        // Constructor
    }

    public ASheetValue(
        @SuppressWarnings("hiding") PExcelSheet _excelSheet_)
    {
        // Constructor
        setExcelSheet(_excelSheet_);

    }

    @Override
    public Object clone()
    {
        return new ASheetValue(
            cloneNode(this._excelSheet_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASheetValue(this);
    }

    public PExcelSheet getExcelSheet()
    {
        return this._excelSheet_;
    }

    public void setExcelSheet(PExcelSheet node)
    {
        if(this._excelSheet_ != null)
        {
            this._excelSheet_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._excelSheet_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._excelSheet_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._excelSheet_ == child)
        {
            this._excelSheet_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._excelSheet_ == oldChild)
        {
            setExcelSheet((PExcelSheet) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
