/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ASheetsWithParamsExcelSheetValue extends PExcelSheetValue
{
    private TSheets _sheets_;
    private PParamCallList _paramCallList_;

    public ASheetsWithParamsExcelSheetValue()
    {
        // Constructor
    }

    public ASheetsWithParamsExcelSheetValue(
        @SuppressWarnings("hiding") TSheets _sheets_,
        @SuppressWarnings("hiding") PParamCallList _paramCallList_)
    {
        // Constructor
        setSheets(_sheets_);

        setParamCallList(_paramCallList_);

    }

    @Override
    public Object clone()
    {
        return new ASheetsWithParamsExcelSheetValue(
            cloneNode(this._sheets_),
            cloneNode(this._paramCallList_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASheetsWithParamsExcelSheetValue(this);
    }

    public TSheets getSheets()
    {
        return this._sheets_;
    }

    public void setSheets(TSheets node)
    {
        if(this._sheets_ != null)
        {
            this._sheets_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sheets_ = node;
    }

    public PParamCallList getParamCallList()
    {
        return this._paramCallList_;
    }

    public void setParamCallList(PParamCallList node)
    {
        if(this._paramCallList_ != null)
        {
            this._paramCallList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._paramCallList_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._sheets_)
            + toString(this._paramCallList_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._sheets_ == child)
        {
            this._sheets_ = null;
            return;
        }

        if(this._paramCallList_ == child)
        {
            this._paramCallList_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._sheets_ == oldChild)
        {
            setSheets((TSheets) newChild);
            return;
        }

        if(this._paramCallList_ == oldChild)
        {
            setParamCallList((PParamCallList) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
