/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ASpaceFunctionValue extends PValue
{
    private PSpaceFunction _spaceFunction_;

    public ASpaceFunctionValue()
    {
        // Constructor
    }

    public ASpaceFunctionValue(
        @SuppressWarnings("hiding") PSpaceFunction _spaceFunction_)
    {
        // Constructor
        setSpaceFunction(_spaceFunction_);

    }

    @Override
    public Object clone()
    {
        return new ASpaceFunctionValue(
            cloneNode(this._spaceFunction_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASpaceFunctionValue(this);
    }

    public PSpaceFunction getSpaceFunction()
    {
        return this._spaceFunction_;
    }

    public void setSpaceFunction(PSpaceFunction node)
    {
        if(this._spaceFunction_ != null)
        {
            this._spaceFunction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._spaceFunction_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._spaceFunction_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._spaceFunction_ == child)
        {
            this._spaceFunction_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._spaceFunction_ == oldChild)
        {
            setSpaceFunction((PSpaceFunction) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
