/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ASplitFunctionWithLimitValue extends PValue
{
    private PSplitFunctionWithLimit _splitFunctionWithLimit_;

    public ASplitFunctionWithLimitValue()
    {
        // Constructor
    }

    public ASplitFunctionWithLimitValue(
        @SuppressWarnings("hiding") PSplitFunctionWithLimit _splitFunctionWithLimit_)
    {
        // Constructor
        setSplitFunctionWithLimit(_splitFunctionWithLimit_);

    }

    @Override
    public Object clone()
    {
        return new ASplitFunctionWithLimitValue(
            cloneNode(this._splitFunctionWithLimit_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASplitFunctionWithLimitValue(this);
    }

    public PSplitFunctionWithLimit getSplitFunctionWithLimit()
    {
        return this._splitFunctionWithLimit_;
    }

    public void setSplitFunctionWithLimit(PSplitFunctionWithLimit node)
    {
        if(this._splitFunctionWithLimit_ != null)
        {
            this._splitFunctionWithLimit_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._splitFunctionWithLimit_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._splitFunctionWithLimit_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._splitFunctionWithLimit_ == child)
        {
            this._splitFunctionWithLimit_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._splitFunctionWithLimit_ == oldChild)
        {
            setSplitFunctionWithLimit((PSplitFunctionWithLimit) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
