/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ASplitFunctionValue extends PValue
{
    private PSplitFunction _splitFunction_;

    public ASplitFunctionValue()
    {
        // Constructor
    }

    public ASplitFunctionValue(
        @SuppressWarnings("hiding") PSplitFunction _splitFunction_)
    {
        // Constructor
        setSplitFunction(_splitFunction_);

    }

    @Override
    public Object clone()
    {
        return new ASplitFunctionValue(
            cloneNode(this._splitFunction_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASplitFunctionValue(this);
    }

    public PSplitFunction getSplitFunction()
    {
        return this._splitFunction_;
    }

    public void setSplitFunction(PSplitFunction node)
    {
        if(this._splitFunction_ != null)
        {
            this._splitFunction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._splitFunction_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._splitFunction_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._splitFunction_ == child)
        {
            this._splitFunction_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._splitFunction_ == oldChild)
        {
            setSplitFunction((PSplitFunction) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
