/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ATrueValue extends PValue
{
    private PBooleanValueTrue _booleanValueTrue_;

    public ATrueValue()
    {
        // Constructor
    }

    public ATrueValue(
        @SuppressWarnings("hiding") PBooleanValueTrue _booleanValueTrue_)
    {
        // Constructor
        setBooleanValueTrue(_booleanValueTrue_);

    }

    @Override
    public Object clone()
    {
        return new ATrueValue(
            cloneNode(this._booleanValueTrue_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATrueValue(this);
    }

    public PBooleanValueTrue getBooleanValueTrue()
    {
        return this._booleanValueTrue_;
    }

    public void setBooleanValueTrue(PBooleanValueTrue node)
    {
        if(this._booleanValueTrue_ != null)
        {
            this._booleanValueTrue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._booleanValueTrue_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._booleanValueTrue_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._booleanValueTrue_ == child)
        {
            this._booleanValueTrue_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._booleanValueTrue_ == oldChild)
        {
            setBooleanValueTrue((PBooleanValueTrue) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
