/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class ATrySetNameTry extends PTry
{
    private TTrySetName _trySetName_;

    public ATrySetNameTry()
    {
        // Constructor
    }

    public ATrySetNameTry(
        @SuppressWarnings("hiding") TTrySetName _trySetName_)
    {
        // Constructor
        setTrySetName(_trySetName_);

    }

    @Override
    public Object clone()
    {
        return new ATrySetNameTry(
            cloneNode(this._trySetName_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATrySetNameTry(this);
    }

    public TTrySetName getTrySetName()
    {
        return this._trySetName_;
    }

    public void setTrySetName(TTrySetName node)
    {
        if(this._trySetName_ != null)
        {
            this._trySetName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._trySetName_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._trySetName_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._trySetName_ == child)
        {
            this._trySetName_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._trySetName_ == oldChild)
        {
            setTrySetName((TTrySetName) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
