/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AUBoundFunctionArithmeticExpressionPartValueNotNegated extends PArithmeticExpressionPartValueNotNegated
{
    private PUBoundFunction _uBoundFunction_;

    public AUBoundFunctionArithmeticExpressionPartValueNotNegated()
    {
        // Constructor
    }

    public AUBoundFunctionArithmeticExpressionPartValueNotNegated(
        @SuppressWarnings("hiding") PUBoundFunction _uBoundFunction_)
    {
        // Constructor
        setUBoundFunction(_uBoundFunction_);

    }

    @Override
    public Object clone()
    {
        return new AUBoundFunctionArithmeticExpressionPartValueNotNegated(
            cloneNode(this._uBoundFunction_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUBoundFunctionArithmeticExpressionPartValueNotNegated(this);
    }

    public PUBoundFunction getUBoundFunction()
    {
        return this._uBoundFunction_;
    }

    public void setUBoundFunction(PUBoundFunction node)
    {
        if(this._uBoundFunction_ != null)
        {
            this._uBoundFunction_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._uBoundFunction_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._uBoundFunction_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._uBoundFunction_ == child)
        {
            this._uBoundFunction_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._uBoundFunction_ == oldChild)
        {
            setUBoundFunction((PUBoundFunction) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
