/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AVarSetIfStmtOneLineValue extends PIfStmtOneLineValue
{
    private PVarSet _varSet_;

    public AVarSetIfStmtOneLineValue()
    {
        // Constructor
    }

    public AVarSetIfStmtOneLineValue(
        @SuppressWarnings("hiding") PVarSet _varSet_)
    {
        // Constructor
        setVarSet(_varSet_);

    }

    @Override
    public Object clone()
    {
        return new AVarSetIfStmtOneLineValue(
            cloneNode(this._varSet_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVarSetIfStmtOneLineValue(this);
    }

    public PVarSet getVarSet()
    {
        return this._varSet_;
    }

    public void setVarSet(PVarSet node)
    {
        if(this._varSet_ != null)
        {
            this._varSet_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varSet_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._varSet_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._varSet_ == child)
        {
            this._varSet_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._varSet_ == oldChild)
        {
            setVarSet((PVarSet) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
