/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AVarDecInWithDataTypeFunctionStmt extends PFunctionStmt
{
    private PVarDecInWithDataType _varDecInWithDataType_;
    private PGeneralStmt _generalStmt_;

    public AVarDecInWithDataTypeFunctionStmt()
    {
        // Constructor
    }

    public AVarDecInWithDataTypeFunctionStmt(
        @SuppressWarnings("hiding") PVarDecInWithDataType _varDecInWithDataType_,
        @SuppressWarnings("hiding") PGeneralStmt _generalStmt_)
    {
        // Constructor
        setVarDecInWithDataType(_varDecInWithDataType_);

        setGeneralStmt(_generalStmt_);

    }

    @Override
    public Object clone()
    {
        return new AVarDecInWithDataTypeFunctionStmt(
            cloneNode(this._varDecInWithDataType_),
            cloneNode(this._generalStmt_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVarDecInWithDataTypeFunctionStmt(this);
    }

    public PVarDecInWithDataType getVarDecInWithDataType()
    {
        return this._varDecInWithDataType_;
    }

    public void setVarDecInWithDataType(PVarDecInWithDataType node)
    {
        if(this._varDecInWithDataType_ != null)
        {
            this._varDecInWithDataType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varDecInWithDataType_ = node;
    }

    public PGeneralStmt getGeneralStmt()
    {
        return this._generalStmt_;
    }

    public void setGeneralStmt(PGeneralStmt node)
    {
        if(this._generalStmt_ != null)
        {
            this._generalStmt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._generalStmt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._varDecInWithDataType_)
            + toString(this._generalStmt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._varDecInWithDataType_ == child)
        {
            this._varDecInWithDataType_ = null;
            return;
        }

        if(this._generalStmt_ == child)
        {
            this._generalStmt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._varDecInWithDataType_ == oldChild)
        {
            setVarDecInWithDataType((PVarDecInWithDataType) newChild);
            return;
        }

        if(this._generalStmt_ == oldChild)
        {
            setGeneralStmt((PGeneralStmt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
