/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AWaitSubFileStmt extends PFileStmt
{
    private PWaitSub _waitSub_;

    public AWaitSubFileStmt()
    {
        // Constructor
    }

    public AWaitSubFileStmt(
        @SuppressWarnings("hiding") PWaitSub _waitSub_)
    {
        // Constructor
        setWaitSub(_waitSub_);

    }

    @Override
    public Object clone()
    {
        return new AWaitSubFileStmt(
            cloneNode(this._waitSub_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAWaitSubFileStmt(this);
    }

    public PWaitSub getWaitSub()
    {
        return this._waitSub_;
    }

    public void setWaitSub(PWaitSub node)
    {
        if(this._waitSub_ != null)
        {
            this._waitSub_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._waitSub_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._waitSub_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._waitSub_ == child)
        {
            this._waitSub_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._waitSub_ == oldChild)
        {
            setWaitSub((PWaitSub) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
