/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AWorksheetsWithParamsExcelSheetValue extends PExcelSheetValue
{
    private TWorksheets _worksheets_;
    private PParamCallList _paramCallList_;

    public AWorksheetsWithParamsExcelSheetValue()
    {
        // Constructor
    }

    public AWorksheetsWithParamsExcelSheetValue(
        @SuppressWarnings("hiding") TWorksheets _worksheets_,
        @SuppressWarnings("hiding") PParamCallList _paramCallList_)
    {
        // Constructor
        setWorksheets(_worksheets_);

        setParamCallList(_paramCallList_);

    }

    @Override
    public Object clone()
    {
        return new AWorksheetsWithParamsExcelSheetValue(
            cloneNode(this._worksheets_),
            cloneNode(this._paramCallList_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAWorksheetsWithParamsExcelSheetValue(this);
    }

    public TWorksheets getWorksheets()
    {
        return this._worksheets_;
    }

    public void setWorksheets(TWorksheets node)
    {
        if(this._worksheets_ != null)
        {
            this._worksheets_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._worksheets_ = node;
    }

    public PParamCallList getParamCallList()
    {
        return this._paramCallList_;
    }

    public void setParamCallList(PParamCallList node)
    {
        if(this._paramCallList_ != null)
        {
            this._paramCallList_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._paramCallList_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._worksheets_)
            + toString(this._paramCallList_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._worksheets_ == child)
        {
            this._worksheets_ = null;
            return;
        }

        if(this._paramCallList_ == child)
        {
            this._paramCallList_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._worksheets_ == oldChild)
        {
            setWorksheets((TWorksheets) newChild);
            return;
        }

        if(this._paramCallList_ == oldChild)
        {
            setParamCallList((PParamCallList) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
