/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

public abstract class PSplitFunctionWithLimit extends Node
{
    // Empty body
}
