/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TChr extends Token
{
    public TChr()
    {
        super.setText("Chr");
    }

    public TChr(int line, int pos)
    {
        super.setText("Chr");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TChr(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTChr(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TChr text.");
    }
}
