/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TDebugPrint extends Token
{
    public TDebugPrint()
    {
        super.setText("Debug.Print");
    }

    public TDebugPrint(int line, int pos)
    {
        super.setText("Debug.Print");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDebugPrint(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDebugPrint(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDebugPrint text.");
    }
}
