/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TDelete extends Token
{
    public TDelete()
    {
        super.setText("Delete");
    }

    public TDelete(int line, int pos)
    {
        super.setText("Delete");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDelete(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDelete(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDelete text.");
    }
}
