/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TDim extends Token
{
    public TDim()
    {
        super.setText("Dim");
    }

    public TDim(int line, int pos)
    {
        super.setText("Dim");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDim(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDim(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDim text.");
    }
}
