/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TDllFunctionToken extends Token
{
    public TDllFunctionToken()
    {
        super.setText("SetHandleCount% Lib \"kernel32\" (ByVal n%)");
    }

    public TDllFunctionToken(int line, int pos)
    {
        super.setText("SetHandleCount% Lib \"kernel32\" (ByVal n%)");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDllFunctionToken(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDllFunctionToken(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDllFunctionToken text.");
    }
}
