/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TDoWhileStart extends Token
{
    public TDoWhileStart()
    {
        super.setText("Do While");
    }

    public TDoWhileStart(int line, int pos)
    {
        super.setText("Do While");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDoWhileStart(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDoWhileStart(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDoWhileStart text.");
    }
}
