/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TEnumEnd extends Token
{
    public TEnumEnd()
    {
        super.setText("End Enum");
    }

    public TEnumEnd(int line, int pos)
    {
        super.setText("End Enum");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TEnumEnd(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTEnumEnd(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TEnumEnd text.");
    }
}
