/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TFullName extends Token
{
    public TFullName()
    {
        super.setText("FullName");
    }

    public TFullName(int line, int pos)
    {
        super.setText("FullName");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFullName(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFullName(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFullName text.");
    }
}
