/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class THidden extends Token
{
    public THidden()
    {
        super.setText("Hidden");
    }

    public THidden(int line, int pos)
    {
        super.setText("Hidden");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new THidden(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTHidden(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change THidden text.");
    }
}
