/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TLof extends Token
{
    public TLof()
    {
        super.setText("LOF");
    }

    public TLof(int line, int pos)
    {
        super.setText("LOF");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TLof(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLof(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TLof text.");
    }
}
