/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TMid extends Token
{
    public TMid()
    {
        super.setText("Mid");
    }

    public TMid(int line, int pos)
    {
        super.setText("Mid");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TMid(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMid(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TMid text.");
    }
}
