/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TMove extends Token
{
    public TMove()
    {
        super.setText("Move");
    }

    public TMove(int line, int pos)
    {
        super.setText("Move");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TMove(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMove(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TMove text.");
    }
}
