/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TOptional extends Token
{
    public TOptional()
    {
        super.setText("Optional");
    }

    public TOptional(int line, int pos)
    {
        super.setText("Optional");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TOptional(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTOptional(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TOptional text.");
    }
}
