/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TPreserve extends Token
{
    public TPreserve()
    {
        super.setText("Preserve");
    }

    public TPreserve(int line, int pos)
    {
        super.setText("Preserve");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPreserve(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPreserve(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPreserve text.");
    }
}
