/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TPrivate extends Token
{
    public TPrivate()
    {
        super.setText("Private");
    }

    public TPrivate(int line, int pos)
    {
        super.setText("Private");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPrivate(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPrivate(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPrivate text.");
    }
}
