/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TRows extends Token
{
    public TRows()
    {
        super.setText("Rows");
    }

    public TRows(int line, int pos)
    {
        super.setText("Rows");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TRows(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTRows(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TRows text.");
    }
}
