/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TSelection extends Token
{
    public TSelection()
    {
        super.setText("Selection");
    }

    public TSelection(int line, int pos)
    {
        super.setText("Selection");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSelection(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSelection(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSelection text.");
    }
}
