/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TSubEnd extends Token
{
    public TSubEnd()
    {
        super.setText("End Sub");
    }

    public TSubEnd(int line, int pos)
    {
        super.setText("End Sub");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSubEnd(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSubEnd(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSubEnd text.");
    }
}
