/* This file was generated by SableCC (http://www.sablecc.org/). */

package com.ibm.ivk.tool.ddlgenerator.sablecc.node;

import com.ibm.ivk.tool.ddlgenerator.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class TVisible extends Token
{
    public TVisible()
    {
        super.setText("Visible");
    }

    public TVisible(int line, int pos)
    {
        super.setText("Visible");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TVisible(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTVisible(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TVisible text.");
    }
}
